[completion]
copilot = false
activate_on_typing = true

[display]
dataframes = "rich"
default_width = "medium"
theme = "system"
code_editor_font_size = 22
cell_output = "above"

[experimental]

[package_management]
manager = "pip"

[save]
autosave = "after_delay"
autosave_delay = 1000
format_on_save = true

[server]
browser = "default"
follow_symlink = false

[keymap]
preset = "vim"

[keymap.overrides]

[ai]
rules = ""
[ai.google]

[ai.anthropic]

[ai.open_ai]

[formatting]
line_length = 79

[runtime]
on_cell_change = "autorun"
std_stream_max_bytes = 1000000
auto_reload = "off"
watcher_on_save = "lazy"
output_max_bytes = 8000000
pythonpath = []
auto_instantiate = true

[language_servers.pylsp]
enable_pyflakes = false
enable_ruff = true
enable_pydocstyle = false
enable_flake8 = false
enable_pylint = false
enable_mypy = true
enabled = true

[snippets]
custom_paths = []
include_default_snippets = true
